[package]
name = "mars-lander-exercise"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name="simulation"
path="src/lib.rs"

[dependencies]
json = "0.12.4"
rand = "0.8"