name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run Pre-Commit Hooks
      run: |
        pip install pre-commit
        pre-commit run --all-files
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  benchmark:
    runs-on: ubuntu-latest
    needs: build  # Ensure this runs after the build job

    steps:
    - uses: actions/checkout@v3

    - name: Run Benchmarks
      run: cargo bench
